modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="territory"
version="${version}"
displayName="Territory"
authors="aruru10313"
description='''Admin-controlled chunk territories with particles and BlueMap 3D overlays.'''

[[dependencies.territory]]
modId="neoforge"
type="required"
versionRange="[21.1.219,)"
ordering="NONE"
side="SERVER"

[[dependencies.territory]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="SERVER"

[[dependencies.territory]]
modId="bluemap"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="SERVER"
